-- 007: additional Holy Land churches (English base rows).
-- Idempotent: re-running deletes these church ids first (children cascade).
BEGIN;

DELETE FROM public.churches WHERE id IN ('10000000-0000-0000-0000-000000000004', '10000000-0000-0000-0000-000000000005', '10000000-0000-0000-0000-000000000006', '10000000-0000-0000-0000-000000000007', '10000000-0000-0000-0000-000000000008', '10000000-0000-0000-0000-000000000009', '10000000-0000-0000-0000-000000000010', '10000000-0000-0000-0000-000000000011', '10000000-0000-0000-0000-000000000012', '10000000-0000-0000-0000-000000000013', '10000000-0000-0000-0000-000000000014', '10000000-0000-0000-0000-000000000015', '10000000-0000-0000-0000-000000000016', '10000000-0000-0000-0000-000000000017');

INSERT INTO public.churches (id, slug, name, name_ar, name_he, status, is_published) VALUES
  ('10000000-0000-0000-0000-000000000004', 'church-of-all-nations-jerusalem', 'Church of All Nations', 'كنيسة جميع الأمم', 'כנסיית כל העמים', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000005', 'church-of-mary-magdalene-jerusalem', 'Church of Mary Magdalene', 'كنيسة مريم المجدلية', 'כנסיית מריה מגדלנה', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000006', 'dominus-flevit-jerusalem', 'Dominus Flevit', 'كنيسة دومينوس فليفيت', 'דומינוס פלויט', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000007', 'church-of-st-anne-jerusalem', 'Church of St. Anne', 'كنيسة القديسة حنة', 'כנסיית סנטה אנה', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000008', 'church-of-the-pater-noster-jerusalem', 'Church of the Pater Noster', 'كنيسة الأبانا', 'כנסיית פאטר נוסטר', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000009', 'church-of-the-visitation-ein-karem', 'Church of the Visitation', 'كنيسة الزيارة', 'כנסיית הביקור', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000010', 'church-of-the-beatitudes-galilee', 'Church of the Beatitudes', 'كنيسة التطويبات', 'כנסיית הר האושר', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000011', 'church-of-the-multiplication-tabgha', 'Church of the Multiplication', 'كنيسة تكثير الخبز والسمك', 'כנסיית הלחם והדגים', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000012', 'church-of-the-primacy-of-st-peter-tabgha', 'Church of the Primacy of St. Peter', 'كنيسة مقام بطرس', 'כנסיית הבכורה של פטרוס', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000013', 'church-of-the-transfiguration-mount-tabor', 'Church of the Transfiguration', 'كنيسة التجلي', 'כנסיית ההשתנות', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000014', 'wedding-church-cana', 'Wedding Church at Cana', 'كنيسة العرس في قانا', 'כנסיית החתונה בכנא', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000015', 'capernaum-st-peters-house', 'Capernaum — St. Peter''s House and Synagogue', 'كفرناحوم — بيت القديس بطرس والكنيس', 'כפר נחום — בית פטרוס ובית הכנסת', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000016', 'shepherds-field-chapel-beit-sahour', 'Shepherds'' Field Chapel', 'كنيسة حقل الرعاة', 'קפלת שדה הרועים', 'LISTED', true),
  ('10000000-0000-0000-0000-000000000017', 'milk-grotto-bethlehem', 'Milk Grotto', 'مغارة الحليب', 'מערת החלב', 'LISTED', true);

INSERT INTO public.church_locations (church_id, address_line1, city, region, country, latitude, longitude) VALUES
  ('10000000-0000-0000-0000-000000000004', 'Gethsemane, Mount of Olives', 'Jerusalem', 'Mount of Olives', 'Israel', 31.7794, 35.2397),
  ('10000000-0000-0000-0000-000000000005', 'Gethsemane, Mount of Olives', 'Jerusalem', 'Mount of Olives', 'Israel', 31.7797, 35.2401),
  ('10000000-0000-0000-0000-000000000006', 'Mount of Olives', 'Jerusalem', 'Mount of Olives', 'Israel', 31.7789, 35.24),
  ('10000000-0000-0000-0000-000000000007', 'Muslim Quarter, near the Pools of Bethesda', 'Jerusalem', 'Old City', 'Israel', 31.7814, 35.2361),
  ('10000000-0000-0000-0000-000000000008', 'Mount of Olives', 'Jerusalem', 'Mount of Olives', 'Israel', 31.7785, 35.2455),
  ('10000000-0000-0000-0000-000000000009', 'Ein Karem', 'Jerusalem', 'Jerusalem District', 'Israel', 31.765, 35.163),
  ('10000000-0000-0000-0000-000000000010', 'Mount of Beatitudes', 'Sea of Galilee', 'Northern District', 'Israel', 32.881, 35.556),
  ('10000000-0000-0000-0000-000000000011', 'Tabgha', 'Sea of Galilee', 'Northern District', 'Israel', 32.873, 35.549),
  ('10000000-0000-0000-0000-000000000012', 'Tabgha', 'Sea of Galilee', 'Northern District', 'Israel', 32.871, 35.55),
  ('10000000-0000-0000-0000-000000000013', 'Summit of Mount Tabor', 'Mount Tabor', 'Northern District', 'Israel', 32.687, 35.39),
  ('10000000-0000-0000-0000-000000000014', 'Kafr Kanna', 'Cana', 'Northern District', 'Israel', 32.749, 35.342),
  ('10000000-0000-0000-0000-000000000015', 'Capernaum, north shore of the Sea of Galilee', 'Capernaum', 'Northern District', 'Israel', 32.881, 35.575),
  ('10000000-0000-0000-0000-000000000016', 'Beit Sahour, near Bethlehem', 'Bethlehem', 'West Bank', 'Palestine', 31.704, 35.224),
  ('10000000-0000-0000-0000-000000000017', 'Milk Grotto Street, Bethlehem, near the Church of the Nativity', 'Bethlehem', 'West Bank', 'Palestine', 31.704, 35.207);

INSERT INTO public.church_visiting_info (church_id, is_open_to_visitors, opening_hours, admission_info, accessibility_info) VALUES
  ('10000000-0000-0000-0000-000000000004', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000005', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000006', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000007', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000008', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000009', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000010', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000011', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000012', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000013', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000014', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000015', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000016', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL),
  ('10000000-0000-0000-0000-000000000017', true, NULL, 'Free admission. Please confirm current visiting hours with the church.', NULL);

INSERT INTO public.church_descriptions (church_id, locale, overview, story, heritage, community) VALUES
  ('10000000-0000-0000-0000-000000000004', 'en', 'The Church of All Nations, also known as the Basilica of the Agony, is a Roman Catholic church at Gethsemane on the Mount of Olives in Jerusalem. It enshrines the section of bedrock traditionally identified as the place where Jesus prayed in agony on the night before his crucifixion.', 'The present basilica was built between 1919 and 1924 on the foundations of earlier Byzantine and Crusader churches uncovered during construction. It became known as the Church of All Nations because donations from many countries funded its building, and their coats of arms are set into the ceiling.', 'The church was designed by the Italian architect Antonio Barluzzi. Before the altar lies the exposed Rock of the Agony, surrounded by a wrought-iron crown of thorns, while the deep violet glass of the windows keeps the interior in a subdued light evoking the night of the Passion. The façade carries a large mosaic depicting Christ as the link between God and humanity.', 'The basilica is cared for by the Franciscan Custody of the Holy Land, which maintains the site and the adjacent Garden of Gethsemane with its ancient olive trees. It remains an active place of prayer and a major stop for pilgrims visiting the Mount of Olives.'),
  ('10000000-0000-0000-0000-000000000005', 'en', 'The Church of Mary Magdalene is a Russian Orthodox church on the western slope of the Mount of Olives in Jerusalem, near the Garden of Gethsemane. It is widely recognized for its seven gilded onion domes, a distinctive landmark of the Jerusalem skyline.', 'The church was built between 1886 and 1888 by Tsar Alexander III of Russia in memory of his mother, Empress Maria Alexandrovna. It was dedicated to Mary Magdalene, the saint after whom the empress was named, and reflects the Russian presence in the Holy Land in the late nineteenth century.', 'Designed in the traditional Muscovite style, the church is crowned by seven gold onion domes and set among gardens above the Kidron Valley. It holds the relics of Grand Duchess Elizabeth Feodorovna, a martyr of the Russian revolution who is venerated as a saint.', 'The church belongs to a convent of Orthodox nuns and remains an active monastic community that welcomes visitors and pilgrims. It stands within the surroundings of Gethsemane on the slopes of the Mount of Olives.'),
  ('10000000-0000-0000-0000-000000000006', 'en', 'Dominus Flevit, meaning "the Lord wept" in Latin, is a Roman Catholic chapel on the western slope of the Mount of Olives in Jerusalem. It marks the place where, according to the Gospel of Luke, Jesus wept as he looked toward Jerusalem and foretold its destruction.', 'The present chapel was built in 1955 on the site of earlier religious buildings, including remains of a Byzantine-era church. Excavations on the grounds also uncovered ancient tombs and ossuaries, testifying to long use of the slope as a burial place.', 'The chapel was designed by the Italian architect Antonio Barluzzi in the shape of a teardrop, recalling the tears of Christ. Its west-facing window frames a sweeping view of the Old City, with the Dome of the Rock and the Church of the Holy Sepulchre visible beyond the altar.', 'Dominus Flevit is maintained by the Franciscan Custody of the Holy Land as part of its network of sanctuaries in and around Jerusalem. It is a frequent stop for pilgrims walking down the Mount of Olives toward Gethsemane.'),
  ('10000000-0000-0000-0000-000000000007', 'en', 'The Church of St. Anne is a Roman Catholic church in the Old City of Jerusalem, in the Muslim Quarter beside the Pools of Bethesda. It stands over a site traditionally venerated as the home of Anne and Joachim and the birthplace of the Virgin Mary.', 'The church was built in the twelfth century during the Crusader Kingdom of Jerusalem. After Saladin''s conquest of the city in 1187 it was converted into an Islamic school, and in the nineteenth century the Ottoman authorities granted it to France, whose custodians restored the building.', 'St. Anne''s is a well-preserved example of Crusader Romanesque architecture, built of pale stone with sturdy pillars and a restrained interior. The church is celebrated for its exceptional acoustics, and visiting groups often pause to sing beneath its high vaults. The adjacent Pools of Bethesda preserve extensive archaeological remains.', 'The church and its grounds are entrusted to the Missionaries of Africa, commonly known as the White Fathers, who care for the site and welcome pilgrims. It remains an active place of prayer and study within the Old City.'),
  ('10000000-0000-0000-0000-000000000008', 'en', 'The Church of the Pater Noster is a Roman Catholic church and Carmelite convent on the Mount of Olives in Jerusalem. It stands on a site traditionally associated with Jesus teaching his disciples the Lord''s Prayer, known in Latin as the Pater Noster.', 'The site preserves the memory of the Byzantine Church of the Eleona, built in the fourth century over a cave on the Mount of Olives during the reign of Constantine. After centuries of ruin, a French convent was established here in the nineteenth century, and construction of church buildings continued into the twentieth century.', 'The compound is best known for its cloister and walls, where the Lord''s Prayer is displayed on decorative ceramic tiles in roughly 140 languages and dialects. Remains of the ancient Eleona basilica and the traditional grotto can also be seen on the grounds.', 'The site is cared for by a community of Carmelite sisters, who maintain the convent, church, and cloister. It is a regular stop for pilgrims and visitors exploring the Mount of Olives.'),
  ('10000000-0000-0000-0000-000000000009', 'en', 'The Church of the Visitation is a Roman Catholic church in the village of Ein Karem, on the western edge of Jerusalem. It marks the traditional site where Mary visited her kinswoman Elizabeth and, according to the Gospel of Luke, spoke the canticle known as the Magnificat. The site is cared for by the Franciscans and is a widely visited destination for pilgrims to the Holy Land.', 'Christian tradition identifies Ein Karem as the home village of Zechariah and Elizabeth and the setting of the Visitation described in Luke''s Gospel. A church stood on the site in the Byzantine and Crusader periods, and the present two-level building preserves elements of these earlier structures. The current church was developed in the first half of the twentieth century under the Franciscan Custody of the Holy Land.', 'The church is built on two levels, with a lower church associated with an ancient spring and older remains, and an upper church added above it. The Italian architect Antonio Barluzzi designed the modern work, which was completed in the 1950s, and the upper church is decorated with large wall paintings. In the adjoining courtyard, the text of the Magnificat is displayed on ceramic tiles in many languages.', 'The site is owned and maintained by the Franciscan Custody of the Holy Land, which cares for numerous shrines across the region. It remains an active place of prayer and a regular stop on pilgrimage routes through Ein Karem, which also contains other churches connected with the birth of John the Baptist.'),
  ('10000000-0000-0000-0000-000000000010', 'en', 'The Church of the Beatitudes is a Roman Catholic church on a hillside above the northwestern shore of the Sea of Galilee. It marks the traditional site of the Sermon on the Mount and takes its name from the Beatitudes, the blessings that open the sermon in the Gospel of Matthew. The setting offers a broad view over the lake and its surrounding villages.', 'The tradition of a hill near Capernaum as the place of the Sermon on the Mount is long-standing, and earlier remains have been noted in the vicinity of Tabgha below. The present church was built in 1938 and designed by the Italian architect Antonio Barluzzi. Its construction was supported in part by funding from Italy.', 'The church has an octagonal plan, its eight sides recalling the eight Beatitudes, and is topped by a dome. A surrounding portico frames views of the Sea of Galilee, and the interior windows carry the Latin texts of the Beatitudes. The building sits within landscaped gardens on the slope of the hill.', 'The church and its grounds are cared for by the Franciscan Missionary Sisters of the Sacred Heart. The site functions as both a place of worship and a widely visited pilgrimage destination in the Galilee.'),
  ('10000000-0000-0000-0000-000000000011', 'en', 'The Church of the Multiplication is a Roman Catholic church at Tabgha, on the northwestern shore of the Sea of Galilee. It commemorates the Gospel account of the multiplication of the loaves and fishes, by which a crowd was fed. The church is well known for its early Christian mosaic floors.', 'Tabgha was venerated in the Byzantine period as the site of the miracle, and a small chapel of the fourth century was later replaced by a larger church in the fifth century. These early buildings fell into ruin, and their remains were rediscovered and excavated in modern times. The present church, built in the twentieth century, reproduces the plan of the Byzantine basilica.', 'The church preserves extensive fifth-century mosaic floors, among the finest surviving in the region, depicting birds, plants, and Nilotic scenes. The best-known panel, set before the altar, shows a basket of loaves flanked by two fish. A rock beneath the altar is traditionally associated with the miracle.', 'The church is served by German Benedictine monks connected with the Dormition Abbey in Jerusalem. It remains an active monastic and pilgrimage site; a fire damaged parts of the complex in 2015, after which it was repaired.'),
  ('10000000-0000-0000-0000-000000000012', 'en', 'The Church of the Primacy of St. Peter is a small Roman Catholic chapel at Tabgha, on the shore of the Sea of Galilee. It commemorates a post-resurrection appearance of Jesus to his disciples described in the Gospel of John and the conferral of primacy upon Peter. The chapel stands directly beside the water.', 'The site recalls the account in John 21, in which the risen Jesus appears to the disciples by the lake, shares a meal of bread and fish, and three times charges Peter to feed his flock. A church associated with this tradition existed here in earlier centuries, and traces of former structures survive nearby. The present chapel was built in 1933.', 'The chapel is constructed of local black basalt, giving it a dark, simple appearance characteristic of Galilee stonework. It is built over a flat rock known as the Mensa Christi, or Table of Christ, traditionally identified with the meal by the shore. Steps carved in the rock lead down to the lake beside the building.', 'The chapel is maintained by the Franciscan Custody of the Holy Land. It is a frequent stop for pilgrims visiting the sites around the northern shore of the Sea of Galilee.'),
  ('10000000-0000-0000-0000-000000000013', 'en', 'The Church of the Transfiguration is a Roman Catholic basilica on the summit of Mount Tabor, which rises above the Jezreel Valley in the Lower Galilee. It commemorates the Transfiguration of Jesus, when according to the Gospels he was seen transformed in the presence of Moses and Elijah. A Greek Orthodox church also stands elsewhere on the mountain.', 'Mount Tabor has been honoured since the Byzantine period as the traditional place of the Transfiguration, and churches were built here in Byzantine and Crusader times. These structures were later ruined, and their foundations remain on the summit. The present basilica was completed in 1924.', 'The basilica was designed by the Italian architect Antonio Barluzzi and rises above the earlier Byzantine and Crusader remains. Its facade is framed by two towers, and two chapels dedicated to Moses and Elijah flank the entrance, recalling the two figures who appear in the Gospel accounts. The upper level holds a mosaic of the Transfiguration above the altar.', 'The basilica and its grounds are cared for by the Franciscan Custody of the Holy Land. The mountain remains a pilgrimage destination, and the summit is shared with a Greek Orthodox monastery and church.'),
  ('10000000-0000-0000-0000-000000000014', 'en', 'The Franciscan Wedding Church stands in Kafr Kanna, the town widely identified with the Cana of Galilee of the Gospels, north of Nazareth. It commemorates the wedding feast at which, according to the Gospel of John, Jesus turned water into wine, described as the first of his signs. The site draws pilgrims, and married couples in particular, who come to mark and renew their vows.', 'The Gospel of John (chapter 2) places Jesus, his mother, and his disciples at a wedding in Cana, where the host ran out of wine and Jesus had six stone jars filled with water that became wine. A church tradition honouring the miracle at Kafr Kanna developed over the centuries, and earlier places of worship stood on or near the present site. The current Franciscan church was built between 1879 and 1905.', 'The church is a masonry basilica with twin bell towers and a dome, built over earlier remains. Excavations beneath and around the building have uncovered ancient structures and vessels associated with the site''s long history of veneration. Old stone jars are displayed in keeping with the Gospel account of the water made wine.', 'The Wedding Church is cared for by the Franciscan friars of the Custody of the Holy Land, who maintain it as a place of worship and pilgrimage. A separate Greek Orthodox church in Kafr Kanna also preserves the tradition of the miracle nearby.'),
  ('10000000-0000-0000-0000-000000000015', 'en', 'Capernaum, on the north shore of the Sea of Galilee, is the lakeside town that the Gospels describe as a centre of Jesus'' ministry in Galilee. The archaeological site preserves the remains venerated as the house of the Apostle Peter and an ancient synagogue. It is one of the most important New Testament sites in the region.', 'The Gospels present Capernaum as the place where Jesus taught, called disciples, and healed, and they associate the town with Peter and other followers. From the early centuries a house at the site was venerated by Christians and later enclosed within an octagonal church. The town was inhabited for centuries before declining, leaving the ruins studied by modern archaeologists.', 'The modern Church of St. Peter, completed in 1990, is raised on pillars over the octagonal remains of the house-church honoured as Peter''s house, allowing visitors to view the older structure below. Nearby stands a synagogue of white limestone built above the remains of an earlier basalt synagogue. Excavations at Capernaum have been carried out largely under Franciscan direction.', 'The site is held and cared for by the Franciscan Custody of the Holy Land, which oversees the church, the excavations, and access for pilgrims and visitors. A separate Greek Orthodox church and monastery stand at the eastern edge of the area.'),
  ('10000000-0000-0000-0000-000000000016', 'en', 'The Shepherds'' Field Chapel stands at Beit Sahour, east of Bethlehem, at the site traditionally identified with the fields of the shepherds in the Nativity story. According to the Gospel of Luke, angels there announced the birth of Jesus to shepherds watching their flocks by night. The chapel and its surrounding grounds are a place of prayer and pilgrimage, especially at Christmas.', 'The Gospel of Luke (chapter 2) describes shepherds near Bethlehem who were told of the Saviour''s birth and went to find the child. Christian veneration of shepherds'' fields near Beit Sahour is very old, and remains of earlier churches and monastic structures have been found in the area. The present Franciscan chapel was built in 1953.', 'Designed by the architect Antonio Barluzzi and completed in 1953, the chapel is shaped to evoke a shepherd''s tent, with a domed interior and windows that admit light in a way suggesting the night of the angelic announcement. Its walls carry paintings depicting scenes from the Nativity narrative. The grounds include remains associated with earlier phases of Christian use.', 'The chapel and its field are cared for by the Franciscan Custody of the Holy Land. A separate Greek Orthodox Shepherds'' Field, with its own church and ancient remains, lies nearby in the same area of Beit Sahour.'),
  ('10000000-0000-0000-0000-000000000017', 'en', 'The Milk Grotto is a chapel built around a soft white chalk grotto in Bethlehem, a short walk from the Church of the Nativity. Tradition connects the grotto with the Holy Family, associating it with the time before or during the flight into Egypt. It is a quiet place of prayer, visited especially by mothers and by couples hoping for children.', 'Local tradition holds that the Holy Family sheltered in this grotto and that its rock turned white, giving rise to the name and to devotions linked to milk and motherhood. Christian veneration of the site is documented over many centuries. The grotto has long been under Franciscan care, and a newer chapel was added in the modern period alongside the older sanctuary.', 'The site centres on a natural grotto of pale, powdery chalk, and the stone itself is central to the devotions practised there. The complex includes a chapel decorated with religious art, built over and around the venerated cave. Its whiteness distinguishes it from the darker rock of the region.', 'The Milk Grotto is cared for by the Franciscan Custody of the Holy Land, who maintain it as a place of prayer and receive pilgrims from many countries. It remains a focus of personal devotion, particularly for those praying for motherhood and family.');

COMMIT;
